# https://commitlint.js.org/#/guides-ci-setup

name: Conventional Commits
on: [push, pull_request]

jobs:
  lint-commits:
    name: Lint Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Commit Linting Tool 🔧
        run: |
          npm install --save-dev @commitlint/{cli,config-conventional}
          npm install --save-dev conventional-changelog-conventionalcommits

      - name: Validate current commit (last commit) with commitlint 🚨
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint 🚨
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
